---
- hosts: localhost
  become: no

  tasks:
  - name: random wait 0-5 seconds
    wait_for:
      timeout: "{{ 40 | random }}"
    register: timeout  
  -name: print msg    
    debug:    
      msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} "
