---
- hosts: localhost
  become: no

  tasks:

  - name: random wait 0-5 seconds
    wait_for:
      timeout: "{{ 40 | random }}"
    msg: "System {{ inventory_hostname }} has uuid {{ ansible_product_uuid }} and waited {{ timeout }} seconds to finish"
