---
- hosts: localhost
  become: no

  tasks:
  - name: random wait 0-5 seconds
    wait_for:
      timeout: "{{ 40 | random }}"
    register: timeout 
    
  - debug:    
      msg: "this job ran on system {{ inventory_hostname }} and waited {{ timeout.elapsed }} seconds to finish "
