---
- hosts: localhost
  become: no

  tasks:

  - name: random wait 0-5 seconds
    wait_for:
      timeout: "{{ 5 | random }}"
      
  - name: 'push metric to dynatrace API'
    uri:
      url: "https://acc.totalapm.idm.atos.net/e/ef713de5-28b4-45ea-9479-d150739df904/api/v2/metrics/ingest"
      status_code: 202
      method: POST
      validate_certs: no
      use_proxy: no
      headers:
        Content-Type: "text/plain"
        Authorization: "Api-token {{ dynatrace_api_token }}"
      body: 'bookings.informationSend,bookingnumber="{{ bookingID }}" 1'

  - name: Post other metric
    uri:
      url: https://ansible.demo.dpm.atos.net/api/v2/job_templates/25/launch/
      user: michiel
      password: admin
      method: POST
        "extra_vars": '{\"bookingID\": ""{{ bookingID }}""}'
      force_basic_auth: yes
      status_code: 201
      body_format: json

